language: cpp

compiler:
  - g++
  - clang

os:
  - linux
  - osx

env:
  - WITH_VTK=OFF
  - WITH_VTK=ON

dist: trusty
sudo: required

before_install: Scripts/install_depends.sh
script:         Scripts/travis.sh

notifications:
  email: false
